# Configuração de Meta-heurísticas para RKO
# Cada meta-heurística listada será executada em uma thread separada
metaheuristics:
  - SA
  - ILS
  - VNS
  - BRKGA
  - BRKGA-CS
  - PSO
  - GA
  - LNS
  - GRASP
  - IPR

# Configurações Gerais de Execução
execution_settings:
  max_runs: 1          # Número máximo de execuções
  debug_mode: 1        # 0: teste, 1: debug
  control_mode: 1      # 0: offline tuning, 1: Q-Learning (online)

# Parâmetros de Algoritmo e Busca
search_parameters:
  local_search_strategy: 1  # 1: first improvement, 2: best improvement
  restart_threshold: 1      # % do tempo máximo para disparar o restart
  elite_pool_size: 10       # Tamanho do pool de soluções de elite